"""Runner: schema-service fetch + retry + JSON summary + audit trail.

Adım 12 PR-2b1 added the retry foundation; PR-2b2a layers the
audit-trail foundation on top. Checkpoint files, resume semantics,
and reports_db writes remain explicitly out of scope (Codex
``019e2a5c`` naming discipline: "audit trail foundation", not
"audit/resume").

Output contract:

* On success: :class:`RunResult` carrying ``run_id`` + ``summary``
  (mirrors the ``fetch-snapshot`` subcommand's stdout JSON shape:
  ``contract_version``, ``allowlist_name``, ``allowlist_version``,
  ``table_count``, ``column_count``) plus ``attempts`` so callers
  see how many tries were needed.
* On failure: the underlying typed exception bubbles up unchanged
  (``SchemaServiceUnavailable``, ``SchemaServiceMalformedResponse``,
  or ``SchemaContractVersionMismatch``). The CLI ``run`` subcommand
  translates these to ``EX_TEMPFAIL`` / ``EX_SOFTWARE`` /
  ``EX_PROTOCOL`` respectively, reusing the PR-2a exit-code matrix.

Audit emission (when an :class:`AuditWriter` is provided):

* ``run_started`` — once at the top of the call
* ``attempt_started`` — once per attempt *after* the backoff sleep
* ``attempt_succeeded`` — on the successful attempt (only one)
* ``attempt_failed`` — every retryable failure (whether or not the
  next attempt will fire) + every terminal failure
* ``run_succeeded`` — once on the successful return path
* ``run_failed`` — once on the failing exit path (terminal failure
  *or* exhausted retry budget)

Absent ``audit`` leaves the PR-2b1 behaviour byte-for-byte
unchanged: no observable side effect beyond ``RunResult`` and the
exception path.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass

from .audit import AuditWriter, build_event
from .checkpoint import CheckpointFile, build_checkpoint, snapshot_signature_for_summary
from .db import ReportsDbWriteError, ReportsDbWriter
from .retry import RetryPolicy, Sleeper, call_with_retry
from .schema_service_client import (
    SchemaContractVersionMismatch,
    SchemaServiceClient,
    SchemaServiceMalformedResponse,
    SchemaServiceUnavailable,
)


@dataclass(frozen=True, slots=True)
class RunResult:
    """Successful fetch outcome carried back to the CLI layer.

    ``summary`` mirrors the ``fetch-snapshot`` subcommand's stdout
    JSON shape so operators see the same fields across both commands.
    ``attempts`` is the number of attempts taken. ``run_id`` is the
    caller-supplied or autogenerated identifier propagated to the
    audit log so operators can correlate stdout / stderr / audit
    events.
    """

    summary: dict[str, object]
    attempts: int
    run_id: str


def run_fetch(
    *,
    client: SchemaServiceClient,
    schema: str | None,
    policy: RetryPolicy,
    sleeper: Sleeper,
    audit: AuditWriter | None = None,
    run_id: str | None = None,
    db_writer: ReportsDbWriter | None = None,
    checkpoint: CheckpointFile | None = None,
    resume: bool = False,
) -> RunResult:
    """Fetch one schema-service snapshot honouring the retry policy.

    Parameters
    ----------
    client:
        Pre-configured :class:`SchemaServiceClient` (the CLI builds it
        from :class:`~etl_worker.config.Config`; tests inject a fake).
    schema:
        Optional ``?schema=`` selector forwarded to
        :meth:`SchemaServiceClient.fetch_snapshot`.
    policy:
        Bounded backoff policy; ``max_attempts == 1`` disables retries.
    sleeper:
        Injectable sleep implementation. Production wires
        :class:`~etl_worker.retry.SystemSleeper`; tests pass a fake.
    audit:
        Optional :class:`~etl_worker.audit.AuditWriter`. When provided,
        the runner emits the event vocabulary documented in the module
        docstring. ``None`` (the default) leaves PR-2b1 behaviour
        intact — no audit side effect.
    run_id:
        Optional caller-supplied run identifier. When omitted the
        runner autogenerates ``uuid.uuid4().hex`` so audit events,
        stdout JSON and CLI stderr can be correlated.

    Raises
    ------
    SchemaServiceUnavailable
        Retry budget exhausted; surfaced unchanged so the CLI can
        return ``EX_TEMPFAIL``.
    SchemaServiceMalformedResponse
        Terminal parse / 4xx failure. Not retried.
    SchemaContractVersionMismatch
        Terminal protocol drift. Not retried.
    """
    rid = run_id if run_id else uuid.uuid4().hex
    if audit is not None:
        audit.write(build_event(run_id=rid, event="run_started"))

    # Resume cursor surface (PR-2b2b): load + emit ``checkpoint_loaded``
    # but never short-circuit fetch/apply. Codex 019e2a5c REVISE absorb:
    # load is **not** gated on the audit writer — operators relying on
    # corrupt-checkpoint detection must see a ``CheckpointError`` even
    # without ``--audit-path``. The audit event is best-effort
    # telemetry on top of that.
    if resume and checkpoint is not None:
        loaded = checkpoint.load()
        if loaded is not None and audit is not None:
            audit.write(
                build_event(
                    run_id=rid,
                    event="checkpoint_loaded",
                    extra={
                        "loaded_run_id": loaded.run_id,
                        "last_successful_attempt": loaded.last_successful_attempt,
                        "snapshot_signature": loaded.snapshot_signature,
                        "written_at": loaded.written_at,
                    },
                )
            )

    def _on_attempt(attempt: int) -> None:
        if audit is not None:
            audit.write(
                build_event(run_id=rid, event="attempt_started", attempt=attempt)
            )

    def _on_failure(attempt: int, error: BaseException, will_retry: bool) -> None:
        if audit is None:
            return
        outcome = _outcome_for_failure(error, will_retry)
        audit.write(
            build_event(
                run_id=rid,
                event="attempt_failed",
                attempt=attempt,
                outcome=outcome,
                error_class=type(error).__name__,
                error_message=str(error),
            )
        )

    def _on_success(attempt: int, _result: object) -> None:
        if audit is None:
            return
        audit.write(
            build_event(
                run_id=rid,
                event="attempt_succeeded",
                attempt=attempt,
                outcome="success",
            )
        )

    try:
        snapshot, attempts = call_with_retry(
            lambda: client.fetch_snapshot(schema=schema),
            retryable=SchemaServiceUnavailable,
            policy=policy,
            sleeper=sleeper,
            on_attempt=_on_attempt,
            on_failure=_on_failure,
            on_success=_on_success,
        )
    except SchemaServiceUnavailable as exc:
        if audit is not None:
            audit.write(
                build_event(
                    run_id=rid,
                    event="run_failed",
                    outcome="retryable_exhausted",
                    error_class=type(exc).__name__,
                    error_message=str(exc),
                )
            )
        raise
    except (SchemaServiceMalformedResponse, SchemaContractVersionMismatch) as exc:
        if audit is not None:
            audit.write(
                build_event(
                    run_id=rid,
                    event="run_failed",
                    outcome=_outcome_for_failure(exc, will_retry=False),
                    error_class=type(exc).__name__,
                    error_message=str(exc),
                )
            )
        raise

    column_count = sum(len(table.columns) for table in snapshot.tables)
    summary: dict[str, object] = {
        "contract_version": snapshot.contract_version,
        "allowlist_name": snapshot.allowlist_name,
        "allowlist_version": snapshot.allowlist_version,
        "table_count": len(snapshot.tables),
        "column_count": column_count,
    }

    # Compute the content-only snapshot signature once: shared by the
    # DB writer (idempotency key) and the checkpoint (operator
    # correlation). Codex 019e2a5c REVISE absorb: the signature is
    # NOT computed inside ``build_checkpoint`` from the full summary
    # because that would mix retry telemetry into the hash.
    signature = snapshot_signature_for_summary(summary)
    db_request_summary = {**summary, "snapshot_signature": signature}

    # PR-2b2b/2b3 transaction boundary: DB upsert happens BEFORE the
    # checkpoint write so we never persist "applied through this point"
    # without an actually applied row. ``db_writer=None`` keeps PR-2b1
    # / PR-2b2a byte-compat behaviour.
    if db_writer is not None:
        if audit is not None:
            audit.write(
                build_event(
                    run_id=rid,
                    event="db_upsert_started",
                    attempt=attempts,
                    extra={"snapshot_signature": signature},
                )
            )
        try:
            result = db_writer.upsert(db_request_summary)
        except ReportsDbWriteError as exc:
            if audit is not None:
                audit.write(
                    build_event(
                        run_id=rid,
                        event="db_upsert_failed",
                        attempt=attempts,
                        outcome="db_write_failure",
                        error_class=type(exc).__name__,
                        error_message=str(exc),
                    )
                )
                audit.write(
                    build_event(
                        run_id=rid,
                        event="run_failed",
                        outcome="db_write_failure",
                        error_class=type(exc).__name__,
                        error_message=str(exc),
                    )
                )
            raise
        if audit is not None:
            audit.write(
                build_event(
                    run_id=rid,
                    event="db_upsert_completed",
                    attempt=attempts,
                    outcome="success",
                    extra={"rows_written": result.rows_written},
                )
            )

    # Checkpoint write happens AFTER successful DB upsert (transaction
    # boundary). When ``db_writer`` is absent, the checkpoint captures
    # "fetched + parsed through this point" — operationally useful as
    # observability even without a real DB applied row.
    if checkpoint is not None:
        cp = build_checkpoint(
            run_id=rid,
            last_successful_attempt=attempts,
            summary={**summary, "attempts": attempts},
        )
        checkpoint.write(cp)
        if audit is not None:
            audit.write(
                build_event(
                    run_id=rid,
                    event="checkpoint_written",
                    attempt=attempts,
                    outcome="success",
                    extra={
                        "snapshot_signature": cp.snapshot_signature,
                        "written_at": cp.written_at,
                    },
                )
            )

    if audit is not None:
        audit.write(
            build_event(
                run_id=rid,
                event="run_succeeded",
                outcome="success",
                summary={**summary, "attempts": attempts},
            )
        )
    return RunResult(summary=summary, attempts=attempts, run_id=rid)


def _outcome_for_failure(error: BaseException, will_retry: bool) -> str:
    """Map an exception + retry decision to the audit ``outcome`` enum."""
    if isinstance(error, SchemaContractVersionMismatch):
        return "contract_drift"
    if isinstance(error, SchemaServiceMalformedResponse):
        return "terminal_failure"
    if isinstance(error, SchemaServiceUnavailable):
        return "retryable_failure" if will_retry else "retryable_exhausted"
    # Defensive fallback — unexpected exception type. The runner's
    # caller surfaces this; the audit event keeps the error class so
    # operators can investigate.
    return "unexpected_failure"
