spring.security.oauth2.resourceserver.jwt.enabled=false
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:127.0.0.1}
eureka.instance.instance-id=${spring.application.name}:${eureka.instance.hostname}:${server.port}
